language: c
sudo: false
cache:
  directories:
    - ~/arduino_ide
    - ~/.arduino15/packages/
git:
  depth: false
  quiet: true
env:
  global:
     - ARDUINO_IDE_VERSION="1.8.8"
before_install:
  - source <(curl -SLs https://raw.githubusercontent.com/adafruit/travis-ci-arduino/master/install.sh)
install:
  - arduino --install-library "Adafruit ESP8266"
  - arduino --install-library "Adafruit BME280 Library"
  - arduino --install-library "Adafruit Unified Sensor"
  - arduino --install-library "ArduinoJson" 5.13.4
  - arduino --install-library "NTPClient"
script:
  - cp bain/secret.h.template bain/secret.h
  - build_platform esp8266